In [ ]:
'''
1. Pytorch Framework - Tensors datatypes
Tensors are similar to numpy arrays, tensors can run on gpus where as numpy arrays cannot run on gpus.
Tenors support Automatic Differentiation
'''

In [3]:
import numpy as np
import torch

In [4]:
data = [[1,2],[3,4]]
#converting this to numpy array
np_array = np.array(data)
print(np_array.shape)
print(np_array)
print(type(np_array))

(2, 2)
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [5]:
torch_tensor = torch.Tensor(data)
print(torch_tensor.shape)
print(torch_tensor)
print(type(torch_tensor))

torch.Size([2, 2])
tensor([[1., 2.],
        [3., 4.]])
<class 'torch.Tensor'>


In [6]:
# Converting numpy array to tenor
x_tensor = torch.from_numpy(np_array)
print(x_tensor)

tensor([[1, 2],
        [3, 4]])


In [7]:
##Create a tensor of all ones similar to x_tensor
x_ones = torch.ones_like(x_tensor)
x_ones

tensor([[1, 1],
        [1, 1]])

In [8]:
##Create a random tensor similar to x_tensor
x_rand = torch.rand_like(x_tensor,dtype=torch.float) #np.float
x_rand

tensor([[0.1235, 0.3606],
        [0.8243, 0.9070]])

In [9]:
shape = (2,3,) #2x3x1

rand_tensor = torch.rand(shape) #np.random.rand
ones_tensor = torch.ones(shape) #np.ones
zeros_tensor = torch.zeros(shape) #np.zeros

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.7081, 0.6042, 0.6775],
        [0.3955, 0.5766, 0.1949]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
print(rand_tensor.shape)

torch.Size([2, 3])


In [13]:
tensor = torch.rand(3,4)
tensor.shape

torch.Size([3, 4])

In [14]:
tensor.dtype

torch.float32

In [15]:
tensor.device

device(type='cpu')

In [16]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
else:
  pass

In [17]:
tensor.device

device(type='cpu')

In [19]:
tensor = torch.ones(4,4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
tensor[0] #First row of the tensor

tensor([1., 1., 1., 1.])

In [22]:
tensor[:,0]

tensor([1., 1., 1., 1.])

In [23]:
tensor[:,-1]

tensor([1., 1., 1., 1.])

In [24]:
## concatenating the tensor
tensor = torch.rand(4,4)
tensor

tensor([[0.1984, 0.0448, 0.7283, 0.4259],
        [0.1021, 0.3194, 0.2152, 0.0213],
        [0.4291, 0.1170, 0.8735, 0.8237],
        [0.4277, 0.3113, 0.2736, 0.6844]])

In [25]:
torch.cat([tensor,tensor,tensor],dim=1) #dim - dimension

tensor([[0.1984, 0.0448, 0.7283, 0.4259, 0.1984, 0.0448, 0.7283, 0.4259, 0.1984,
         0.0448, 0.7283, 0.4259],
        [0.1021, 0.3194, 0.2152, 0.0213, 0.1021, 0.3194, 0.2152, 0.0213, 0.1021,
         0.3194, 0.2152, 0.0213],
        [0.4291, 0.1170, 0.8735, 0.8237, 0.4291, 0.1170, 0.8735, 0.8237, 0.4291,
         0.1170, 0.8735, 0.8237],
        [0.4277, 0.3113, 0.2736, 0.6844, 0.4277, 0.3113, 0.2736, 0.6844, 0.4277,
         0.3113, 0.2736, 0.6844]])

In [26]:
## Arithemetic Operations
t1 = torch.rand(2,2)
t2 = torch.rand(2,2)

y1 = t1 @ t2.T ##or
y2 = t1.matmul(t2.T)

In [27]:
y1

tensor([[0.1386, 0.1422],
        [0.5811, 0.4398]])

In [28]:
y2

tensor([[0.1386, 0.1422],
        [0.5811, 0.4398]])

In [30]:
## [2x2] and [2x2]
z1 = t1*t2
z1

tensor([[0.0981, 0.0405],
        [0.2561, 0.1837]])

In [31]:
z2 = t1.mul(t2) #matmul does matrix multiplication : mul does elementwise multiplication

In [32]:
t1

tensor([[0.1138, 0.2091],
        [0.5804, 0.4175]])

In [34]:
agg = t1.sum()
agg

tensor(1.3208)

In [35]:
agg.item()

1.3207939863204956

In [36]:
t1 = torch.ones(4,4)
t1[:,1] = 0
t1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [37]:
t1.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [38]:
x = np.array([[1,2],[3,4]])
tensor = torch.from_numpy(x) #convert it into tensor
y = tensor.numpy()#convert it to numpy array


In [39]:
type(x)

numpy.ndarray

In [40]:
type(tensor)

torch.Tensor

In [41]:
type(y)

numpy.ndarray